services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/tcp"
      - "67:67/udp"
    restart: always
    volumes:
      - dnsmasq:/etc/dnsmasq.d
      - pihole:/etc/pihole
    networks:
      - frontend
    labels:
      - 'pihole.url=${PIHOLE_DOMAIN:-dns.home}'
      - 'traefik.enable=true'
      - 'traefik.http.routers.pihole.rule=Host(`${PIHOLE_DOMAIN:-dns.home}`)'
      - 'traefik.http.routers.pihole.entrypoints=websecure'
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - 'traefik.http.routers.pihole.tls=true'
      - 'traefik.http.routers.pihole.tls.certresolver=letsencrypt'

  autolocaldns:
    build:
      context: auto_local_dns
      dockerfile: Dockerfile
    image: pihole_autolocaldns
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - pihole:/etc/pihole
    environment:
      - "SCHEDULE_SECONDS=${PIHOLE_AUTO_LOCAL_DNS_SCHEDULE:-30}"
      - "LABEL_URL=${PIHOLE_AUTO_LOCAL_DNS_LABEL_DOMAIN:-pihole.url}"
      - "DOCKER_NETWORK=frontend"
      - "DOMAIN_EXTENSION=${PIHOLE_AUTO_LOCAL_DNS_DOMAIN_EXTENSION:-home}"
      - "PIHOLE_DNS_LIST_PATH=/etc/pihole/custom.list"

volumes:
  dnsmasq:
    external: false
  pihole:
    external: false

networks:
  frontend:
    external: true
