services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/tcp"
      - "67:67/udp"
    restart: always
    volumes:
      - pihole-dnsmasq:/etc/dnsmasq.d
      - pihole-pihole:/etc/pihole
    networks:
      - frontend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pihole.rule=Host(`dns.local`)'
      - 'traefik.http.routers.pihole.entrypoints=web'
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

volumes:
  pihole-dnsmasq:
    external: true
  pihole-pihole:
    external: true

networks:
  frontend:
    external: true
