services:
  traefik:
    depends_on:
      - dockerproxy
    image: traefik
    networks:
      - frontend
    ports:
      - 80:80
      - 443:443
      - 8079:8080
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ${TRAEFIK_ETC:-.}:/etc/traefik
    labels:
      - 'pihole.url=traefik.home'
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.rule=Host(`traefik.home`)'
      - 'traefik.http.routers.traefik.entrypoints=web'
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"


networks:
  frontend:
    external: true
