log:
  level: DEBUG  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: common  # common, json, logfmt
  filePath: /var/log/traefik/traefik.log
# 
# # (Optional) Accesslog
# # ---
# # accesslog:
#   # format: common  # common, json, logfmt
#     # filePath: /var/log/traefik/access.log
#      
#      # (Optional) Enable API and Dashboard
#      # ---
api:
  dashboard: true  # true by default
  insecure: true  # Don't do this in production!
#
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
                      
providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: "dannj75@gmail.com"
      storage: /etc/traefik/certs/acme.json
      # caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
      tlsChallenge: {}
